## **Prever se o câncer é benigno ou maligno**

In [263]:
import numpy as np
import pandas as pd

In [264]:
df = pd.read_csv('Dados/data.csv',
                    sep=',', encoding='iso-8859-1')

In [265]:
df.head(20)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0     842302         M        17.99         10.38          122.80     1001.0   
1     842517         M        20.57         17.77          132.90     1326.0   
2   84300903         M        19.69         21.25          130.00     1203.0   
3   84348301         M        11.42         20.38           77.58      386.1   
4   84358402         M        20.29         14.34          135.10     1297.0   
5     843786         M        12.45         15.70           82.57      477.1   
6     844359         M        18.25         19.98          119.60     1040.0   
7   84458202         M        13.71         20.83           90.20      577.9   
8     844981         M        13.00         21.82           87.50      519.8   
9   84501001         M        12.46         24.04           83.97      475.9   
10    845636         M        16.02         23.24          102.70      797.8   
11  84610002         M        15.78         17.89          103.60      781.0   
12    846226         M        19.17         24.80          132.40     1123.0   
13    846381         M        15.85         23.95          103.70      782.7   
14  84667401         M        13.73         22.61           93.60      578.3   
15  84799002         M        14.54         27.54           96.73      658.8   
16    848406         M        14.68         20.13           94.74      684.5   
17  84862001         M        16.13         20.68          108.10      798.8   
18    849014         M        19.81         22.15          130.00     1260.0   
19   8510426         B        13.54         14.36           87.46      566.3   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.11840           0.27760         0.30010              0.14710   
1           0.08474           0.07864         0.08690              0.07017   
2           0.10960           0.15990         0.19740              0.12790   
3           0.14250           0.28390         0.24140              0.10520   
4           0.10030           0.13280         0.19800              0.10430   
5           0.12780           0.17000         0.15780              0.08089   
6           0.09463           0.10900         0.11270              0.07400   
7           0.11890           0.16450         0.09366              0.05985   
8           0.12730           0.19320         0.18590              0.09353   
9           0.11860           0.23960         0.22730              0.08543   
10          0.08206           0.06669         0.03299              0.03323   
11          0.09710           0.12920         0.09954              0.06606   
12          0.09740           0.24580         0.20650              0.11180   
13          0.08401           0.10020         0.09938              0.05364   
14          0.11310           0.22930         0.21280              0.08025   
15          0.11390           0.15950         0.16390              0.07364   
16          0.09867           0.07200         0.07395              0.05259   
17          0.11700           0.20220         0.17220              0.10280   
18          0.09831           0.10270         0.14790              0.09498   
19          0.09779           0.08129         0.06664              0.04781   

    ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0   ...          17.33           184.60      2019.0            0.1622   
1   ...          23.41           158.80      1956.0            0.1238   
2   ...          25.53           152.50      1709.0            0.1444   
3   ...          26.50            98.87       567.7            0.2098   
4   ...          16.67           152.20      1575.0            0.1374   
5   ...          23.75           103.40       741.6            0.1791   
6   ...          27.66           153.20      1606.0            0.1442   
7   ...          28.14           110.60       897.0            0.1654   
8   ...          30.73           

In [266]:
df.shape

(569, 33)

## **Transformando as classes strings em variáveis categóricas ordinais**

In [267]:
df2 = pd.DataFrame.copy(df)

In [268]:
df2['diagnosis'].replace({'M':0, 'B': 1}, inplace=True)


In [269]:
df2.dtypes

id                           int64
diagnosis                    int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst     

## **ATRIBUTOS PREVISORES E ALVO**

In [270]:
previsores = df2.iloc[:, 2:32].values

In [271]:
previsores


array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [272]:
previsores.shape

(569, 30)

In [273]:
alvo = df2.iloc[:, 1:2].values

In [274]:
alvo

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [275]:
alvo.shape

(569, 1)

## **Análise das escalas dos atributos (Escalonamento)**

In [276]:
df2.describe()

id   diagnosis  radius_mean  texture_mean  perimeter_mean  \
count  5.690000e+02  569.000000   569.000000    569.000000      569.000000   
mean   3.037183e+07    0.627417    14.127292     19.289649       91.969033   
std    1.250206e+08    0.483918     3.524049      4.301036       24.298981   
min    8.670000e+03    0.000000     6.981000      9.710000       43.790000   
25%    8.692180e+05    0.000000    11.700000     16.170000       75.170000   
50%    9.060240e+05    1.000000    13.370000     18.840000       86.240000   
75%    8.813129e+06    1.000000    15.780000     21.800000      104.100000   
max    9.113205e+08    1.000000    28.110000     39.280000      188.500000   

         area_mean  smoothness_mean  compactness_mean  concavity_mean  \
count   569.000000       569.000000        569.000000      569.000000   
mean    654.889104         0.096360          0.104341        0.088799   
std     351.914129         0.014064          0.052813        0.079720   
min     143.500000         0.052630          0.019380        0.000000   
25%     420.300000         0.086370          0.064920        0.029560   
50%     551.100000         0.095870          0.092630        0.061540   
75%     782.700000         0.105300          0.130400        0.130700   
max    2501.000000         0.163400          0.345400        0.426800   

       concave points_mean  ...  texture_worst  perimeter_worst   area_worst  \
count           569.000000  ...     569.000000       569.000000   569.000000   
mean              0.048919  ...      25.677223       107.261213   880.583128   
std               0.038803  ...       6.146258        33.602542   569.356993   
min               0.000000  ...      12.020000        50.410000   185.200000   
25%               0.020310  ...      21.080000        84.110000   515.300000   
50%               0.033500  ...      25.410000        97.660000   686.500000   
75%               0.074000  ...      29.720000       125.400000  1084.000000   
max               0.201200  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 33 columns]

In [277]:
from sklearn.preprocessing import StandardScaler

In [278]:
previsores_esc = StandardScaler().fit_transform(previsores) #Esc de escalonado

In [279]:
previsores_esc

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [280]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

0         1         2         3         4         5         6   \
0    1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1    1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2    1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3   -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4    1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   
..        ...       ...       ...       ...       ...       ...       ...   
564  2.110995  0.721473  2.060786  2.343856  1.041842  0.219060  1.947285   
565  1.704854  2.085134  1.615931  1.723842  0.102458 -0.017833  0.693043   
566  0.702284  2.045574  0.672676  0.577953 -0.840484 -0.038680  0.046588   
567  1.838341  2.336457  1.982524  1.735218  1.525767  3.272144  3.296944   
568 -1.808401  1.221792 -1.814389 -1.347789 -3.112085 -1.150752 -1.114873   

           7         8         9   ...        20        21        22  \
0    2.532475  2.217515  2.255747  ...  1.886690 -1.359293  2.303601   
1    0.548144  0.001392 -0.868652  ...  1.805927 -0.369203  1.535126   
2    2.037231  0.939685 -0.398008  ...  1.511870 -0.023974  1.347475   
3    1.451707  2.867383  4.910919  ... -0.281464  0.133984 -0.249939   
4    1.428493 -0.009560 -0.562450  ...  1.298575 -1.466770  1.338539   
..        ...       ...       ...  ...       ...       ...       ...   
564  2.320965 -0.312589 -0.931027  ...  1.901185  0.117700  1.752563   
565  1.263669 -0.217664 -1.058611  ...  1.536720  2.047399  1.421940   
566  0.105777 -0.809117 -0.895587  ...  0.561361  1.374854  0.579001   
567  2.658866  2.137194  1.043695  ...  1.961239  2.237926  2.303601   
568 -1.261820 -0.820070 -0.561032  ... -1.410893  0.764190 -1.432735   

           23        24        25        26        27        28        29  
0    2.001237  1.307686  2.616665  2.109526  2.296076  2.750622  1.937015  
1    1.890489 -0.375612 -0.430444 -0.146749  1.087084 -0.243890  0.281190  
2    1.456285  0.527407  1.082932  0.854974  1.955000  1.152255  0.201391  
3   -0.550021  3.394275  3.893397  1.989588  2.175786  6.046041  4.935010  
4    1.220724  0.220556 -0.313395  0.613179  0.729259 -0.868353 -0.397100  
..        ...       ...       ...       ...       ...       ...       ...  
564  2.015301  0.378365 -0.273318  0.664512  1.629151 -1.360158 -0.709091  
565  1.494959 -0.691230 -0.394820  0.236573  0.733827 -0.531855 -0.973978  
566  0.427906 -0.809587  0.350735  0.326767  0.414069 -1.104549 -0.318409  
567  1.653171  1.430427  3.904848  3.197605  2.289985  1.919083  2.219635  
568 -1.075813 -1.859019 -1.207552 -1.305831 -1.745063 -0.048138 -0.751207  

[569 rows x 30 columns]

In [281]:
previsoresdf.describe()

0             1             2             3             4   \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean  -1.373633e-16  6.868164e-17 -1.248757e-16 -2.185325e-16 -8.366672e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -2.029648e+00 -2.229249e+00 -1.984504e+00 -1.454443e+00 -3.112085e+00   
25%   -6.893853e-01 -7.259631e-01 -6.919555e-01 -6.671955e-01 -7.109628e-01   
50%   -2.150816e-01 -1.046362e-01 -2.359800e-01 -2.951869e-01 -3.489108e-02   
75%    4.693926e-01  5.841756e-01  4.996769e-01  3.635073e-01  6.361990e-01   
max    3.971288e+00  4.651889e+00  3.976130e+00  5.250529e+00  4.770911e+00   

                 5             6             7             8             9   \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean   1.873136e-16  4.995028e-17 -4.995028e-17  1.748260e-16  4.745277e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -1.610136e+00 -1.114873e+00 -1.261820e+00 -2.744117e+00 -1.819865e+00   
25%   -7.470860e-01 -7.437479e-01 -7.379438e-01 -7.032397e-01 -7.226392e-01   
50%   -2.219405e-01 -3.422399e-01 -3.977212e-01 -7.162650e-02 -1.782793e-01   
75%    4.938569e-01  5.260619e-01  6.469351e-01  5.307792e-01  4.709834e-01   
max    4.568425e+00  4.243589e+00  3.927930e+00  4.484751e+00  4.910919e+00   

       ...            20            21            22          23  \
count  ...  5.690000e+02  5.690000e+02  5.690000e+02  569.000000   
mean   ... -8.241796e-16  1.248757e-17 -3.746271e-16    0.000000   
std    ...  1.000880e+00  1.000880e+00  1.000880e+00    1.000880   
min    ... -1.726901e+00 -2.223994e+00 -1.693361e+00   -1.222423   
25%    ... -6.749213e-01 -7.486293e-01 -6.895783e-01   -0.642136   
50%    ... -2.690395e-01 -4.351564e-02 -2.859802e-01   -0.341181   
75%    ...  5.220158e-01  6.583411e-01  5.402790e-01    0.357589   
max    ...  4.094189e+00  3.885905e+00  4.287337e+00    5.930172   

                 24            25            26            27            28  \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean  -2.372638e-16 -3.371644e-16  7.492542e-17  2.247763e-16  2.622390e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -2.682695e+00 -1.443878e+00 -1.305831e+00 -1.745063e+00 -2.160960e+00   
25%   -6.912304e-01 -6.810833e-01 -7.565142e-01 -7.563999e-01 -6.418637e-01   
50%   -4.684277e-02 -2.695009e-01 -2.182321e-01 -2.234689e-01 -1.274095e-01   
75%    5.975448e-01  5.396688e-01  5.311411e-01  7.125100e-01  4.501382e-01   
max    3.955374e+00  5.112877e+00  4.700669e+00  2.685877e+00  6.046041e+00   

                 29  
count  5.690000e+02  
mean  -5.744282e-16  
std    1.000880e+00  
min   -1.601839e+00  
25%   -6.919118e-01  
50%   -2.164441e-01  
75%    4.507624e-01  
max    6.846856e+00  

[8 rows x 30 columns]

### **OneHotEncoder: Criação de variáveis Dummy (fictícia).criando variaveis ficticiais**

In [282]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [283]:
previsores3 = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,2,6,8,10])],
                                remainder='passthrough').fit_transform(previsoresdf)

In [284]:
previsores3.shape

(569, 2535)

In [285]:
previsores3df = pd.DataFrame(previsores3)
previsores3df.head()

0
0    (0, 1)\t1.0\n  (0, 934)\t1.0\n  (0, 1522)\t1...
1    (0, 186)\t1.0\n  (0, 965)\t1.0\n  (0, 1322)\...
2    (0, 324)\t1.0\n  (0, 957)\t1.0\n  (0, 1479)\...
3    (0, 297)\t1.0\n  (0, 643)\t1.0\n  (0, 1508)\...
4    (0, 60)\t1.0\n  (0, 972)\t1.0\n  (0, 1481)\t...

## **Escalonamento**

In [286]:
from sklearn.preprocessing import StandardScaler

In [287]:
previsores3_esc = StandardScaler().fit_transform(previsoresdf)

## **BASE DE TREINO E TESTE**

In [288]:
from sklearn.model_selection import train_test_split

In [289]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size = 0.3, random_state = 0)

In [290]:
x_treino.shape

(398, 30)

In [291]:
x_teste.shape

(171, 30)

In [292]:
y_treino.shape

(398, 1)

In [293]:
y_teste.shape

(171, 1)

# **CRIAÇÃO DO ALGORITMO**

In [294]:
from sklearn.neural_network import MLPClassifier

In [295]:
redes = MLPClassifier(hidden_layer_sizes=(7), activation='relu', solver='adam', max_iter =1200, #Para ter duas camadas ocultas em hidden_layer_sizes? Basta colocar (7,7).
                              tol=0.0001, random_state = 12, verbose = True)

In [296]:
redes.fit(x_treino, y_treino)

c:\Users\ALV\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 11.66195345
Iteration 2, loss = 11.10696841
Iteration 3, loss = 10.36409538
Iteration 4, loss = 9.40522879
Iteration 5, loss = 8.07939671
Iteration 6, loss = 6.64190513
Iteration 7, loss = 5.32340708
Iteration 8, loss = 4.58050792
Iteration 9, loss = 4.25764747
Iteration 10, loss = 4.45109296
Iteration 11, loss = 4.73649604
Iteration 12, loss = 4.94045624
Iteration 13, loss = 4.94206845
Iteration 14, loss = 4.75036319
Iteration 15, loss = 4.45059834
Iteration 16, loss = 4.12859988
Iteration 17, loss = 3.85549219
Iteration 18, loss = 3.74639467
Iteration 19, loss = 3.70480228
Iteration 20, loss = 3.69442489
Iteration 21, loss = 3.66389270
Iteration 22, loss = 3.60923040
Iteration 23, loss = 3.51362956
Iteration 24, loss = 3.39324157
Iteration 25, loss = 3.27483491
Iteration 26, loss = 3.18179164
Iteration 27, loss = 3.11950313
Iteration 28, loss = 3.06745904
Iteration 29, loss = 3.01464169
Iteration 30, loss = 2.94554633
Iteration 31, loss = 2.87462295
Iteration 32, 

Iteration 718, loss = 0.20445037
Iteration 719, loss = 0.20490412
Iteration 720, loss = 0.20434835
Iteration 721, loss = 0.20448208
Iteration 722, loss = 0.20435858
Iteration 723, loss = 0.20395130
Iteration 724, loss = 0.20394717
Iteration 725, loss = 0.20355594
Iteration 726, loss = 0.20451516
Iteration 727, loss = 0.20332299
Iteration 728, loss = 0.20449862
Iteration 729, loss = 0.20321617
Iteration 730, loss = 0.20300495
Iteration 731, loss = 0.20288167
Iteration 732, loss = 0.20266915
Iteration 733, loss = 0.20386926
Iteration 734, loss = 0.20273146
Iteration 735, loss = 0.20290222
Iteration 736, loss = 0.20202448
Iteration 737, loss = 0.20235460
Iteration 738, loss = 0.20248791
Iteration 739, loss = 0.20232848
Iteration 740, loss = 0.20173224
Iteration 741, loss = 0.20176944
Iteration 742, loss = 0.20198207
Iteration 743, loss = 0.20225535
Iteration 744, loss = 0.20129030
Iteration 745, loss = 0.20122542
Iteration 746, loss = 0.20110477
Iteration 747, loss = 0.20083003
Iteration 

c:\Users\ALV\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=7, max_iter=1200, random_state=12,
              verbose=True)

In [297]:
previsoes = redes.predict(x_teste)

In [298]:
previsoes

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [299]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [300]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes) * 100.0))

Acurácia: 95.32%


In [301]:
confusion_matrix(y_teste, previsoes)

array([[ 59,   4],
       [  4, 104]], dtype=int64)

**Análise dados de treino**

In [302]:
previsoes_treino = redes.predict(x_treino)
previsoes_treino

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,

In [303]:
accuracy_score(y_treino, previsoes_treino)

0.9321608040201005